export const sharedStyles = {
  content: {
    maxWidth: 1100,
    margin: "0 auto",
    padding: "0 32px",
  },
  sectionWrap: {
    paddingTop: 100,
    paddingBottom: 60,
  },
  card: {
    background: "#13121E",
    border: "1px solid #ffffff0d",
    borderRadius: 16,
    padding: 28,
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 20,
  },
  pill: {
    display: "inline-block",
    background: "#1E1B2E",
    border: "1px solid #7C3AED44",
    color: "#C4B5FD",
    borderRadius: 100,
    padding: "6px 14px",
    fontSize: 13,
    fontWeight: 500,
    margin: "4px",
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    background: "#7C3AED",
    flexShrink: 0,
    marginTop: 6,
    boxShadow: "0 0 8px #7C3AED88",
  },
  btnPrimary: {
    background: "linear-gradient(135deg, #7C3AED, #5B21B6)",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "13px 28px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    letterSpacing: 0.5,
    boxShadow: "0 4px 24px #7C3AED44",
  },
};
